# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bde98323a8ea54ca87dc34c5aa6610287df28b529f4e1a55c157922d11dd357ad2c4d5eeeb5bb8786d61920b613a8698b63c100456bec7730ff1c85c1133695

test:
  secret_key_base: 583f72b23fa12e01107ec4d7ec53b4eb51ebecfa52320046c7bb65b6c26306213597a4eb238f2f3f01273c8bf88226517b59ea62554fe709c47c2489c7c3a8f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
